import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Gofitish creatores tool dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          backgroundImage: `url(/images/img5.jpeg)`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backfaceVisibility: "visible",
          backgroundPosition: "center top",
        }}
      >
        <div
          className="h-screen w-screen flex flex-col justify-center items-center"
          style={{
            background:
              "linear-gradient(to right,rgba(255,255,255,.5) 30%,rgba(255,255,255,.4) 70% ",
          }}
        >
          <div className="bg-gray-200 rounded-2xl p-4 text-center">
            <h1 className="font-bold text-xl text-gray-900 mb-4">
              Abeg jump to dashboard Nothing is functional yet ooo!
            </h1>
            <button className="mb-4 bg-slate-900 rounded-full ring-1 ring-slate-900 hover:bg-slate-700 text-white px-4 py-1 uppercase text-base font-normal">
              <Link href="/emmanuel/dashboard">Dashboard</Link>
            </button>
            <div className="border-[.001rem] border-gray-300 mb-3"></div>
            <div className="flex justify-evenly items-center">
              <button className="mb-4 mr-4 bg-slate-900 rounded-full ring-1 ring-slate-900 hover:bg-slate-700 text-white px-6 py-1 uppercase text-base font-normal">
                <Link href="/auth/login">Login</Link>
              </button>
              <button className="mb-4 bg-slate-900 rounded-full ring-1 ring-slate-900 hover:bg-slate-700 text-white px-4 py-1 uppercase text-base font-normal">
                <Link href="/auth/create-account">Create Account</Link>
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
