import Head from "next/head";

function Layout(props) {
  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Gofitish creators {props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50  w-11/12 md:w-4/12 p-3 shadow ">
        <h1 className="text-slate-800 font-bold text-xl text-center">
          {props.head}
        </h1>
        {props.children}
      </div>
    </div>
  );
}

export default Layout;
